changelog:
  exclude:
    labels:
      - "changelog: none"
    authors:
      - dependabot
      - github-actions

  categories:
    - title: [Add] New Features 🎉
      labels:
        - "changelog: add"
        - "type: enhancement"

    - title: [Update] Updated ✨
      labels:
        - "changelog: update"

    - title: [Fix] Fixes 🛠
      labels:
        - "changelog: fix"
        - "type: bug"

    - title: [Tweak] Tweaked 🔧
      labels:
        - "changelog: tweak"
        - "type: technical debt"

    - title: Other Changes
      labels:
        - "*"
