name: Prepare Node
description: Load npm cache, install Node dependencies

inputs:
  ignore-scripts:
    description: Whether to run `npm ci` with --ignore-scripts. "yes" by default.
    required: false
    default: "yes"

runs:
  using: composite
  steps:
    # Setup node version from .`nvmrc, and caching.
    - uses: actions/setup-node@v2
      id: setup-node
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    # Log debug information.
    - shell: sh -e {0}
      run: |
        node --version
        npm --version

    # Install node dependencies.
    - shell: sh -e {0}
      # `actions/setup-node` should update npm cache directory if `package-lock` has changed.
      run: |
        if [ [ "${{ steps.setup-node.outputs.cache-hit }}" != "true" ]; then
          npm ci `if [ "${{ inputs.ignore-scripts }}" = "yes" ]; then printf %s "--ignore-scripts"; fi`
        else
          echo "Skip npm ci"
        fi
