name: Bundle Size

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:

jobs:
  BundleSize:
    name: Bundle size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.21.0"
          cache: "npm"

      - name: Log debug information
        run: |
          php --version
          composer --version
          node --version
          npm --version

      - name: Get Composer cache directory
        id: composer-cache-config
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Set up Composer caching
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-config.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Node dependencies
        run: npm ci

      - name: Build production bundle
        run: |
          echo "::group::Build log"
          npm run build
          echo "::endgroup::"

      # Since BundleWatch is having issues when getting some environment variables from GitHub Actions,
      # it needs some workarounds to specify `CI_COMMIT_SHA`, `CI_BRANCH`, and `CI_BRANCH_BASE` here.
      # References:
      # - https://github.com/bundlewatch/bundlewatch/blob/v0.3.2/src/app/config/getCIVars.js#L8-L10
      # - https://github.com/bundlewatch/bundlewatch/issues/423
      # - https://github.com/bundlewatch/bundlewatch/issues/220
      - name: Prepare BundleWatch env values - push
        if: ${{ github.event_name == 'push' }}
        run: |
          BRANCH=$(echo '${{ github.event.ref }}' | sed 's/^refs\/heads\///')
          echo "CI_BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "CI_BRANCH_BASE=$BRANCH" >> $GITHUB_ENV

      - name: Prepare BundleWatch env values - pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "CI_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "CI_BRANCH_BASE=${{ github.base_ref }}" >> $GITHUB_ENV

      - name: Run BundleWatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_COMMIT_SHA: ${{ github.sha }}
        run: node ./node_modules/bundlewatch/lib/bin/index.js
