name: JavaScript and CSS Linting

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:

env:
  FORCE_COLOR: 2
jobs:
  Setup:
    name: Setup for jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare node
        uses: ./.github/actions/prepare-node

  JSLintingCheck:
    name: Lint JavaScript
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare node
        uses: ./.github/actions/prepare-node

      - name: Lint JavaScript and annotate linting errors
        run: npm run lint:js -- --format ./.github/scripts/eslintFormatter.js

  CSSLintingCheck:
    name: Lint CSS
    needs: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare node
        uses: ./.github/actions/prepare-node

      - name: Lint CSS and annotate linting errors
        run: npm run lint:css -- --custom-formatter ./.github/scripts/stylelintFormatter.js
