name: JavaScript and CSS Linting

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  JSLintingCheck:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare node
        uses: ./.github/actions/prepare-node

      - name: Lint JavaScript and annotate linting errors
        run: npm run lint:js -- --quiet --format ./.github/scripts/eslintFormatter.js

  CSSLintingCheck:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare node
        uses: ./.github/actions/prepare-node

      - name: Lint CSS and annotate linting errors
        run: npm run lint:css -- --custom-formatter ./.github/scripts/stylelintFormatter.js
