name: PHP Unit Tests

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.php"
      - ./composer.json
      - ./composer.lock
      - ./.github/workflows/php-unit-tests.yml
      - ./.github/actions/prepare-php/action.yml
  pull_request:
    paths:
      - "**.php"
      - ./composer.json
      - ./composer.lock
      - ./.github/workflows/php-unit-tests.yml
      - ./.github/actions/prepare-php/action.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Setup:
    name: Setup for jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare PHP
        uses: ./.github/actions/prepare-php
        with:
          install-deps: "maybe"

  UnitTests:
    name: PHP unit tests - PHP ${{ matrix.php }}, WP ${{ matrix.wp-version }}
    needs: Setup
    runs-on: ubuntu-latest
    env:
      WP_CORE_DIR: "/tmp/wordpress/src"
      WP_TESTS_DIR: "/tmp/wordpress/tests/phpunit"
    strategy:
      matrix:
        php: [7.3, 7.4, 8.0]
        wp-version: [5.7, 5.8, latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare PHP
        uses: ./.github/actions/prepare-php
        with:
          php-version: "${{ matrix.php }}"

      - name: Set up MySQL
        # MySQL 8.0 uses the `caching_sha2_password` authentication method by default.
        # So here alter password with `mysql_native_password` authentication method
        # to make older PHP (7.3.x) mysql client be able to create database connections.
        run: |
          sudo systemctl start mysql.service
          mysql -u root -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

      - name: Install WP tests
        shell: bash
        run: ./bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wp-version }}

      - name: PHP8 & PHPUnit9 with WordPress greater than v5.8
        run: |
          php_version=${{matrix.php}}
          wp_version=${{matrix.wp-version}}
          php_version_check=$(echo "$php_version >= 8" |bc -l)
          wp_version_latest=$(echo "$wp_version == latest" |bc -l)
          wp_version_higher=$(echo "$wp_version > 5.8" |bc -l)
          if [[ $php_version_check -eq 1 && ( $wp_version_latest -eq 1 || $wp_version_higher -eq 1 ) ]] ; then
            composer require phpunit/phpunit "^9.5" --dev --update-with-all-dependencies
          fi

      - name: Run PHP unit tests
        run: composer test-unit
